version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - SERVICES=lambda,apigateway,cognito,dynamodb,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.localstack:/var/lib/localstack'
