name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC, adjust as needed

jobs:
  terraform-cleanup:
    name: "Post Apply Cleanup"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub repository"
        uses: actions/checkout@v2

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./terraform

      - name: "Terraform Plan Destroy"
        run: terraform plan -destroy -out=tfplan-destroy
        working-directory: ./terraform

      - name: "Terraform Apply Destroy"
        run: terraform apply -auto-approve tfplan-destroy
        working-directory: ./terraform
